version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-openai"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data_prod:/var/lib/weaviate
    restart: always
    networks:
      - portfolio-network

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app_prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEAVIATE_PORT=8080
      - WEAVIATE_HOST=weaviate
    env_file:
      - .env
    depends_on:
      - weaviate
    restart: always
    networks:
      - portfolio-network

networks:
  portfolio-network:

volumes:
  weaviate_data_prod:
