version: '3.8'

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "1564:8080"
      - "50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: "text2vec-openai"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      CLUSTER_HOSTNAME: "node1"
    restart: always